apiVersion: v1
kind: ConfigMap
metadata:
  name: freeverse-configmap
data:
  freeverse_username: freeverse
  freeverse_password: freeverse

  market_id: "sk_production_AjWbpOPwS3HNi821Ma9mIgA2"
  notary_process_wait: 30

  PROXY_CONTRACT_ADDRESS: 0x7334A1E445B4E1Fb94001E1a9F772212b6D9de46

  BLOCKS_PER_STEP: "1000"
  domain: "https://market.goalrevolution.live"
  SYNC_CONFIG_FILE: "config_prod.json"
