apiVersion: v1
kind: ConfigMap
metadata:
  name: freeverse-configmap
data:
  freeverse_username: freeverse
  freeverse_password: freeverse

  market_id: ""
  notary_extra_args: "-iap_test"
  notary_process_wait: "90"
  authproxy_extra_args: "-backdoor"
  horizon_extra_args: "--enableCors"
  mailbox_cron: "* * * * *"
  PROXY_CONTRACT_ADDRESS: 0x720C10669287462Bb96eFd9bb5220EcfcBfd88cf

  BLOCKS_PER_STEP: "10000"
  domain: "*"
  SYNC_CONFIG_FILE: "config_dev.json"
