version: '3'
services:
  ethereum: 
    image: freeverseio/ethereum:$TAG
    command: --mine --bootnodes ${ENODE}
    ports: 
      - "30303:30303"
      - "30303:30303/udp"
    volumes:
      - ethereum-data:/test
  universe.db:
    image: freeverseio/universe.db:$TAG
  synchronizer:
    image: freeverseio/synchronizer:$TAG
    command: > 
      -postgres postgres://freeverse:freeverse@universe.db:5432/cryptosoccer?sslmode=disable 
      -ethereum http://ethereum:8545
      -leaguesContractAddress "${LEAGUES_CONTRACT_ADDRESS}"
      -engineContractAddress "${ENGINE_CONTRACT_ADDRESS}"
      -enginePreCompContractAddress "${ENGINEPRECOMP_CONTRACT_ADDRESS}"
      -marketContractAddress "${MARKET_CONTRACT_ADDRESS}"
      -updatesContractAddress "${UPDATES_CONTRACT_ADDRESS}"
      -assetsContractAddress "${ASSETS_CONTRACT_ADDRESS}"
      -evolutionContractAddress "${EVOLUTION_CONTRACT_ADDRESS}"
    depends_on:
      - universe.db
      - ethereum
  universe.api:
    image: freeverseio/universe.api:$TAG
    depends_on:
      - universe.db
    command: -d postgres://freeverse:freeverse@universe.db:5432/cryptosoccer
    ports:
      - "4005:4000"
  market.db:
    image: freeverseio/market.db:$TAG
  market.trader:
    image: freeverseio/market.trader:$TAG
    command: -d postgres://freeverse:freeverse@market.db:5432/market -p 4000
    ports:
      - "4002:4000"
  market.notary:
    image: freeverseio/market.notary:$TAG
    depends_on:
      - ethereum
    command: >
      -postgres postgres://freeverse:freeverse@market.db:5432/market?sslmode=disable  
      -private_key "3B878F7892FBBFA30C8AED1DF317C19B853685E707C2CF0EE1927DC516060A54" 
      -ethereum http://ethereum:8545 
      -market_address "${MARKET_CONTRACT_ADDRESS}" 
  relay.api:
    image: freeverseio/relay.api:$TAG
    depends_on:
      - ethereum
    ports:
      - "4003:4000"
    command: >
      -d postgres://freeverse:freeverse@relay.db:5432/relay
      --assetsContractAddress "${ASSETS_CONTRACT_ADDRESS}" 
      --privateKey "5d0060adb17bd80efd7fff71e718bdd97acf3c6e0c633d8f7fd451044c0d1480" 
      --ethereum "http://ethereum:8545"
  relay.db:
    image: freeverseio/relay.db:$TAG
  horizon:
    image: freeverseio/horizon:$TAG
    depends_on:
      - universe.api
      - market.trader
      - relay.api
    command: >
      -u http://universe.api:4000/graphql 
      -m http://market.trader:4000/graphql 
      -r http://relay.api:4000/graphql
    ports:
      - "4000:4000"
  relay.actions:
    image: freeverseio/relay.actions:$TAG
    depends_on:
      - ethereum
      - ipfs
    command: >
      -postgres postgres://freeverse:freeverse@relay.db:5432/relay?sslmode=disable  
      -private_key "3b650bb692288ea5d4c99c2d3e1eb77972eaeebdb04f6b2610a7d7f42de0ad27" 
      -ethereum "http://ethereum:8545"
      -updatesContractAddress "${UPDATES_CONTRACT_ADDRESS}" 
      -delay 60s
      -ipfs ipfs.node:5001
  ipfs.node:
    image: ipfs/go-ipfs:v0.4.22
    environment:
      - IPFS_PROFILE=server
      - IPFS_PATH=/data
    ports:
      # - "4001:4001"
      # - "127.0.0.1:8080:8080"
      # - "127.0.0.1:8081:8081"
      - "127.0.0.1:5001:5001"
    volumes:
      - ipfs.node-data:/data
volumes:
  ethereum-data:
  ipfs.node-data:
